server:
  port: 7002
  servlet:
    session:
      timeout: 300
logging:
  level:
    org.springframework.web: debug
    com.mq: debug

spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.127:3306/rbac_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 0
    cache: false
  redis:
    cluster:
      nodes: 192.168.0.127:6380,192.168.0.127:6381,192.168.0.127:6382,192.168.0.127:6383,192.168.0.127:6384,192.168.0.127:6385
      max-redirects: 6
    timeout: 300000
    jedis:
      pool:
        max-active: 8
        max-wait: 100000
        max-idle: 8
        min-idle: 0
    message:
      top-name: topic-test
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml